services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: erp-api:latest
    container_name: erp-api
    restart: unless-stopped
    env_file:
      - .env.prod
    environment:
      - GO_ENV=production

  erp-frontend:
    build:
      context: ../FE-ERP
      dockerfile: Dockerfile
    image: erp-frontend:latest
    container_name: erp-frontend
    restart: unless-stopped

  landing:
    image: invorya-erp-ludoia-web
    container_name: landing-web
    restart: unless-stopped
    environment:
      - HOSTNAME=0.0.0.0
      - HOST=0.0.0.0
      - PORT=3000

  caddy:
    image: caddy:2-alpine
    container_name: erp-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - api
      - erp-frontend
      - landing

volumes:
  caddy_data:
  caddy_config: